scheduleonce/once-ui-react

package-lock.json, package.json
vite package update from 4.5.2 to 4.5.3
=> vite package update from 4.5.2 to 4.5.3

package-lock.json, package.json
updated tar package from 6.2.0 to 6.2.1
=> updated tar package from 6.2.0 to 6.2.1

package.json, src/lib/components/multi-select/multi-select.module.scss, src/lib/components/multi-select/multi-select.stories.tsx, src/lib/components/multi-select/multi-select.tsx
Fixed issue related to select your option visibility in multiselect
https://scheduleonce.atlassian.net/browse/ONCEHUB-80684
=> Fixed issue related to select your option visibility in multiselect

package-lock.json, package.json, src/lib/components/scrollbar/scrollbar.module.css, src/lib/components/scrollbar/scrollbar.tsx
https://scheduleonce.atlassian.net/browse/ONCEHUB-80685
=> update the scrollbar UI and release verion to 1.4.5

package.json, src/lib/components/checkbox/checkbox.module.scss
Fixed Booking Calendar CF UI is breaking in a scenario for Firefox browser
=> Fixed Booking Calendar CF UI is breaking in a scenario for Firefox browser

package-lock.json, package.json, src/lib/components/common/pseudo-checkbox/psuedo-checkbox.module.scss, src/lib/components/multi-select/multi-select.module.scss, src/lib/components/select/options.tsx, src/lib/components/select/select-options.tsx
https://scheduleonce.atlassian.net/browse/ONCEHUB-77453
allow multiline in select options
=> allow multiline in select options

package-lock.json, package.json, src/lib/components/quick-multi-select/quick-multi-select.module.scss
fix text issue for quick multi select
=>  fix text issue for quick multi select

src/lib/components/multi-select/multi-select.module.scss
=> fix text overflow issue

package-lock.json, package.json
=> update the version

package-lock.json, src/lib/components/select/select.stories.tsx
fix build issue and storybook select issue
=> fix build issue and storybook select issue

package.json, src/lib/components/select/select.stories.tsx
fix: Single Select dropdown fix in storybook
=> fix: Single Select dropdown fix in storybook

package.json, src/lib/components/select/auto-complete.stories.tsx
=> Added autocomplete story

package-lock.json, package.json
https://scheduleonce.atlassian.net/browse/ONCEHUB-83087
=> fixed vulnerability and updated the version of once-ui-react

package-lock.json, package.json, src/lib/components/multi-select/multi-select.module.scss, src/lib/components/multi-select/multi-select.tsx, src/lib/components/select/auto-complete-options.tsx, src/lib/components/select/auto-complete.module.scss, src/lib/components/select/auto-complete.stories.tsx, src/lib/components/select/auto-complete.tsx, src/lib/components/select/index.tsx, src/lib/components/select/select-options.tsx, src/lib/components/select/select.module.scss, src/lib/components/select/select.stories.tsx, src/lib/components/select/select.tsx
move tailwind classes from html to .scss files to resolve the tailwind classes conflicts.
=> move tailwind classes from html to .scss files.

package-lock.json, package.json
updated the once-ui-react version to 1.4.19
=> updated the once-ui-react version to 1.4.19

package-lock.json, package.json, src/lib/components/select/auto-complete.tsx, src/lib/components/select/select.tsx
https://scheduleonce.atlassian.net/browse/ONCEHUB-88408
fix select and autocomplete disabled UI issue.
=> fix select and autocomplete disabled UI issue.

package-lock.json, package.json, src/lib/components/select/auto-complete.tsx
https://scheduleonce.atlassian.net/browse/ONCEHUB-75025
Focus was getting stuck on single select on safari browser due to component re-rendering.
=> fix : single select focus issue for Safari browser.

package-lock.json, package.json, src/lib/components/multi-select/multi-select.tsx, src/lib/components/select/select.tsx
https://scheduleonce.atlassian.net/browse/ONCEHUB-75025
fix : select focus issue for Safari browser
=> fix : select focus issue for Safari browser

package-lock.json, package.json, src/lib/components/select/auto-complete.tsx, src/lib/components/select/select.tsx
https://scheduleonce.atlassian.net/browse/ONCEHUB-75025
Fix select auto focus issue for Safari browser.
=>  select focus issue for Safari browser

package-lock.json, package.json
Peer dependencies chaneged to react 19
"peerDependencies": {
"react": "^19.0.0",
"react-dom": "^19.0.0"
}
=> chore: update version to 2.0.0 in package.json and package-lock.json

package-lock.json
https://scheduleonce.atlassian.net/browse/ONCEHUB-93038
=> CVE-2025-24010 vulnerability found in package vite in project once-ui-react

package-lock.json, package.json, src/lib/components/index.ts, src/lib/components/radio/README.md, src/lib/components/radio/index.tsx, src/lib/components/radio/radio.module.scss, src/lib/components/radio/radio.stories.tsx, src/lib/components/radio/radio.tsx
This pull request introduces a new `Radio` component to the `@oncehub/ui-react` library, along with its associated styles, documentation, and Storybook stories. Additionally, it updates the library's version and exports the new component for use.
* **Component Implementation**: Added the `Radio` component, a customizable radio button with theming support, in `src/lib/components/radio/radio.tsx`. It includes props for `name`, `checked`, `onChange`, `option`, and `themeColor`. The component supports accessibility and avatar display.
* **Styling**: Introduced `radio.module.scss` with Tailwind CSS utilities for styling the `Radio` component, including its wrapper, label, input, and visual states.
* **Documentation**: Added a `README.md` file for the `Radio` component, detailing its usage, …
=> Added new radio button component
